cluster:
  name: my-cluster
externalServices:
  prometheus:
    host: COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI
    basicAuth:
      username: "COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI"
      password: COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI
  loki:
    host: COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI
    basicAuth:
      username: "COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI"
      password: COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI
  tempo:
    host: COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI
    basicAuth:
      username: "COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI"
      password: COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: my-cluster
    prometheus:
      external:
        url: COMES_FROM_GRAFANA_K8S_INTEGRATION_SETUP_UI
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-events: {}
alloy-logs: {}

